# Generated by Django 4.2.18 on 2025-03-16 09:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('container', '0004_alter_dockerimage_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='项目名称')),
                ('description', models.TextField(blank=True, verbose_name='项目描述')),
                ('project_type', models.CharField(choices=[('ide', 'IDE开发环境'), ('notebook', 'Jupyter Notebook'), ('canvas', '可视化拖拽编程')], default='ide', max_length=20, verbose_name='项目类型')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_public', models.BooleanField(default=False, verbose_name='是否公开')),
                ('status', models.CharField(choices=[('creating', '创建中'), ('running', '运行中'), ('stopped', '已停止'), ('error', '错误')], default='creating', max_length=20, verbose_name='状态')),
                ('container', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project', to='container.containerinstance', verbose_name='关联容器')),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='projects', to='container.dockerimage', verbose_name='使用镜像')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to=settings.AUTH_USER_MODEL, verbose_name='创建者')),
            ],
            options={
                'verbose_name': '项目',
                'verbose_name_plural': '项目',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProjectFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='文件名称')),
                ('path', models.CharField(max_length=1000, verbose_name='文件路径')),
                ('content_type', models.CharField(max_length=100, verbose_name='内容类型')),
                ('size', models.IntegerField(default=0, verbose_name='文件大小')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='project.project', verbose_name='关联项目')),
            ],
            options={
                'verbose_name': '项目文件',
                'verbose_name_plural': '项目文件',
                'ordering': ['path', 'name'],
            },
        ),
    ]
