# Generated by Django 4.2.18 on 2025-04-07 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_alter_project_project_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='project_type',
            field=models.CharField(choices=[('notebook', 'Jupyter Notebook'), ('canvas', '可视化拖拽编程')], default='notebook', max_length=20, verbose_name='项目类型'),
        ),
    ]
