# Generated by Django 4.2.13 on 2025-04-27 09:27

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_alter_project_project_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Workflow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='工作流名称')),
                ('description', models.TextField(blank=True, verbose_name='工作流描述')),
                ('definition', models.JSONField(default=dict, verbose_name='工作流定义')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('version', models.IntegerField(default=1, verbose_name='版本号')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workflows', to='project.project', verbose_name='关联项目')),
            ],
            options={
                'verbose_name': '工作流',
                'verbose_name_plural': '工作流',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='WorkflowExecution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', '等待中'), ('running', '运行中'), ('completed', '已完成'), ('failed', '失败'), ('canceled', '已取消')], default='pending', max_length=20, verbose_name='状态')),
                ('start_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='开始时间')),
                ('end_time', models.DateTimeField(blank=True, null=True, verbose_name='结束时间')),
                ('logs', models.TextField(blank=True, verbose_name='执行日志')),
                ('result', models.JSONField(blank=True, default=dict, verbose_name='执行结果')),
                ('workflow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='executions', to='project.workflow', verbose_name='关联工作流')),
            ],
            options={
                'verbose_name': '工作流执行记录',
                'verbose_name_plural': '工作流执行记录',
                'ordering': ['-start_time'],
            },
        ),
        migrations.CreateModel(
            name='WorkflowComponentExecution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('node_id', models.CharField(max_length=50, verbose_name='节点ID')),
                ('component_id', models.CharField(max_length=50, verbose_name='组件ID')),
                ('component_name', models.CharField(max_length=100, verbose_name='组件名称')),
                ('status', models.CharField(choices=[('pending', '等待中'), ('running', '运行中'), ('completed', '已完成'), ('failed', '失败'), ('skipped', '已跳过')], default='pending', max_length=20, verbose_name='状态')),
                ('start_time', models.DateTimeField(blank=True, null=True, verbose_name='开始时间')),
                ('end_time', models.DateTimeField(blank=True, null=True, verbose_name='结束时间')),
                ('inputs', models.JSONField(blank=True, default=dict, verbose_name='输入参数')),
                ('outputs', models.JSONField(blank=True, default=dict, verbose_name='输出结果')),
                ('error', models.TextField(blank=True, verbose_name='错误信息')),
                ('execution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='component_executions', to='project.workflowexecution', verbose_name='关联工作流执行')),
            ],
            options={
                'verbose_name': '组件执行记录',
                'verbose_name_plural': '组件执行记录',
                'ordering': ['start_time'],
            },
        ),
    ]
