# Generated by Django 4.2.13 on 2025-03-17 07:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='JupyterSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(blank=True, max_length=64, null=True, verbose_name='访问令牌')),
                ('url', models.CharField(blank=True, max_length=255, null=True, verbose_name='访问URL')),
                ('status', models.CharField(choices=[('creating', '创建中'), ('running', '运行中'), ('stopped', '已停止'), ('error', '错误')], default='creating', max_length=20, verbose_name='状态')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='jupyter_session', to='project.project', verbose_name='关联项目')),
            ],
            options={
                'verbose_name': 'Jupyter会话',
                'verbose_name_plural': 'Jupyter会话',
            },
        ),
    ]
