# Generated by Django 4.2.18 on 2025-03-19 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jupyterapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jupytersession',
            name='port',
            field=models.IntegerField(blank=True, default=8888, null=True, verbose_name='端口号'),
        ),
    ]
