# Generated by Django 4.2.18 on 2025-04-14 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jupyterapp', '0002_jupytersession_port'),
    ]

    operations = [
        migrations.AddField(
            model_name='jupytersession',
            name='container_id',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='Docker容器ID'),
        ),
    ]
