# Generated by Django 4.2.18 on 2025-04-14 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jupyterapp', '0004_jupytersession_workspace_dir'),
    ]

    operations = [
    ]
