# Generated by Django 4.2.18 on 2025-04-14 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jupyterapp', '0005_merge_20250414_2142'),
        ('jupyterapp', '0006_jupytersession_process_id'),
    ]

    operations = [
    ]
