# Generated by Django 4.2.18 on 2025-04-14 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jupyterapp', '0007_merge_20250414_2146'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jupytersession',
            name='container_id',
        ),
        migrations.AlterField(
            model_name='jupytersession',
            name='port',
            field=models.IntegerField(blank=True, null=True, verbose_name='端口号'),
        ),
    ]
