# Generated by Django 4.2.18 on 2025-02-13 14:51

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ResourceQuota",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "max_containers",
                    models.IntegerField(
                        default=5,
                        help_text="最大容器数量",
                        validators=[django.core.validators.MinValueValidator(1)],
                    ),
                ),
                (
                    "max_cpu",
                    models.IntegerField(
                        default=4,
                        help_text="最大CPU使用量(核)",
                        validators=[django.core.validators.MinValueValidator(1)],
                    ),
                ),
                (
                    "max_memory",
                    models.IntegerField(
                        default=8192,
                        help_text="最大内存使用量(MB)",
                        validators=[django.core.validators.MinValueValidator(1024)],
                    ),
                ),
                (
                    "max_gpu",
                    models.IntegerField(
                        default=1,
                        help_text="最大GPU使用量(个)",
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, help_text="创建时间"),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, help_text="更新时间")),
                (
                    "user",
                    models.OneToOneField(
                        help_text="关联用户",
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DockerImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(help_text="镜像名称", max_length=100)),
                ("tag", models.CharField(help_text="镜像标签/版本", max_length=50)),
                ("description", models.TextField(help_text="镜像描述")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, help_text="创建时间"),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, help_text="更新时间")),
                (
                    "min_cpu",
                    models.IntegerField(
                        default=1,
                        help_text="最小CPU需求(核)",
                        validators=[django.core.validators.MinValueValidator(1)],
                    ),
                ),
                (
                    "min_memory",
                    models.IntegerField(
                        default=1024,
                        help_text="最小内存需求(MB)",
                        validators=[django.core.validators.MinValueValidator(512)],
                    ),
                ),
                (
                    "min_gpu",
                    models.IntegerField(
                        default=0,
                        help_text="最小GPU需求(个)",
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                ("is_active", models.BooleanField(default=True, help_text="是否可用")),
            ],
            options={
                "ordering": ["-created_at"],
                "unique_together": {("name", "tag")},
            },
        ),
        migrations.CreateModel(
            name="ContainerInstance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "container_id",
                    models.CharField(
                        help_text="Docker容器ID", max_length=100, unique=True
                    ),
                ),
                ("name", models.CharField(help_text="容器名称", max_length=100)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("created", "已创建"),
                            ("running", "运行中"),
                            ("paused", "已暂停"),
                            ("stopped", "已停止"),
                            ("deleted", "已删除"),
                        ],
                        default="created",
                        help_text="容器状态",
                        max_length=20,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, help_text="创建时间"),
                ),
                (
                    "started_at",
                    models.DateTimeField(blank=True, help_text="启动时间", null=True),
                ),
                (
                    "cpu_limit",
                    models.IntegerField(
                        help_text="CPU限制(核)",
                        validators=[django.core.validators.MinValueValidator(1)],
                    ),
                ),
                (
                    "memory_limit",
                    models.IntegerField(
                        help_text="内存限制(MB)",
                        validators=[django.core.validators.MinValueValidator(512)],
                    ),
                ),
                (
                    "gpu_limit",
                    models.IntegerField(
                        default=0,
                        help_text="GPU限制(个)",
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "image",
                    models.ForeignKey(
                        help_text="使用的镜像",
                        on_delete=django.db.models.deletion.PROTECT,
                        to="container.dockerimage",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="关联用户",
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
