# Generated by Django 4.2.18 on 2025-03-10 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('container', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dockerimage',
            name='image_tag',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Docker镜像标签'),
        ),
    ]
