# Generated by Django 4.2.18 on 2025-03-10 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('container', '0002_dockerimage_image_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dockerimage',
            name='status',
            field=models.CharField(choices=[('pending', '等待中'), ('building', '构建中'), ('ready', '就绪'), ('failed', '失败'), ('canceled', '已取消')], default='pending', max_length=20, verbose_name='状态'),
        ),
    ]
