# Generated by Django 4.2.18 on 2025-03-16 13:37

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('container', '0004_alter_dockerimage_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='dockerimage',
            name='build_log',
            field=models.TextField(blank=True, null=True, verbose_name='构建日志'),
        ),
        migrations.AddField(
            model_name='dockerimage',
            name='dockerfile',
            field=models.TextField(blank=True, null=True, verbose_name='Dockerfile内容'),
        ),
        migrations.AddField(
            model_name='dockerimage',
            name='error_message',
            field=models.TextField(blank=True, null=True, verbose_name='错误信息'),
        ),
        migrations.AddField(
            model_name='dockerimage',
            name='image_type',
            field=models.CharField(blank=True, choices=[('ide', 'IDE开发环境'), ('notebook', 'Jupyter Notebook'), ('canvas', '可视化拖拽编程'), ('base', '基础镜像')], default='base', max_length=20, null=True, verbose_name='镜像类型'),
        ),
        migrations.AddField(
            model_name='dockerimage',
            name='min_cpu',
            field=models.FloatField(blank=True, default=1, null=True, verbose_name='最小CPU核心数'),
        ),
        migrations.AddField(
            model_name='dockerimage',
            name='min_gpu',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='最小GPU数量'),
        ),
        migrations.AddField(
            model_name='dockerimage',
            name='min_memory',
            field=models.IntegerField(blank=True, default=1024, null=True, verbose_name='最小内存(MB)'),
        ),
        migrations.CreateModel(
            name='Container',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('docker_id', models.CharField(blank=True, max_length=64, null=True, verbose_name='Docker容器ID')),
                ('name', models.CharField(max_length=100, verbose_name='容器名称')),
                ('status', models.CharField(choices=[('created', '已创建'), ('running', '运行中'), ('exited', '已停止'), ('paused', '已暂停'), ('restarting', '重启中'), ('removing', '删除中'), ('error', '错误')], default='created', max_length=20, verbose_name='状态')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('port_mappings', models.JSONField(blank=True, null=True, verbose_name='端口映射')),
                ('environment', models.JSONField(blank=True, null=True, verbose_name='环境变量')),
                ('volumes', models.JSONField(blank=True, null=True, verbose_name='数据卷')),
                ('container_logs', models.TextField(blank=True, null=True, verbose_name='容器日志')),
                ('exit_code', models.IntegerField(blank=True, null=True, verbose_name='退出代码')),
                ('error_message', models.TextField(blank=True, null=True, verbose_name='错误信息')),
                ('ide_ready', models.BooleanField(default=False, verbose_name='IDE服务就绪')),
                ('ide_url', models.CharField(blank=True, max_length=200, null=True, verbose_name='IDE URL')),
                ('ide_startup_logs', models.TextField(blank=True, null=True, verbose_name='IDE启动日志')),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='containers', to='container.dockerimage', verbose_name='镜像')),
            ],
            options={
                'verbose_name': '容器',
                'verbose_name_plural': '容器',
                'ordering': ['-created_at'],
            },
        ),
    ]
