# Generated by Django 4.2.18 on 2025-04-07 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('container', '0005_dockerimage_build_log_dockerimage_dockerfile_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dockerimage',
            name='use_slim',
            field=models.BooleanField(default=True, verbose_name='使用slim版本'),
        ),
    ]
