# Generated by Django 4.2.18 on 2025-04-07 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('container', '0006_dockerimage_use_slim'),
    ]

    operations = [
        migrations.AddField(
            model_name='dockerimage',
            name='actual_version',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='实际Python版本'),
        ),
    ]
