# Generated by Django 4.2.18 on 2025-04-09 12:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('container', '0008_dockerimage_cuda_version_dockerimage_pytorch_version'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dockerimage',
            name='cuda_version',
        ),
        migrations.RemoveField(
            model_name='dockerimage',
            name='pytorch_version',
        ),
    ]
