# Generated by Django 4.2.18 on 2025-04-19 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('container', '0008_dockerimage_cuda_available_dockerimage_cuda_version_and_more'),
    ]

    operations = [
        migrations.RunSQL(
            """
            SELECT COUNT(*) INTO @exist_is_pytorch FROM information_schema.COLUMNS 
            WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'container_dockerimage' AND COLUMN_NAME = 'is_pytorch';
            
            SET @stmt = IF(@exist_is_pytorch = 0, 
                'ALTER TABLE container_dockerimage ADD COLUMN is_pytorch BOOLEAN DEFAULT FALSE',
                'SELECT 1');
            PREPARE stmt FROM @stmt;
            EXECUTE stmt;
            DEALLOCATE PREPARE stmt;
            """,
            reverse_sql="SELECT 1;"
        ),
        migrations.RunSQL(
            """
            SELECT COUNT(*) INTO @exist_pytorch_version FROM information_schema.COLUMNS 
            WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'container_dockerimage' AND COLUMN_NAME = 'pytorch_version';
            
            SET @stmt = IF(@exist_pytorch_version = 0, 
                'ALTER TABLE container_dockerimage ADD COLUMN pytorch_version VARCHAR(10) NULL',
                'SELECT 1');
            PREPARE stmt FROM @stmt;
            EXECUTE stmt;
            DEALLOCATE PREPARE stmt;
            """,
            reverse_sql="SELECT 1;"
        ),
        migrations.RunSQL(
            """
            SELECT COUNT(*) INTO @exist_cuda_version FROM information_schema.COLUMNS 
            WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'container_dockerimage' AND COLUMN_NAME = 'cuda_version';
            
            SET @stmt = IF(@exist_cuda_version = 0, 
                'ALTER TABLE container_dockerimage ADD COLUMN cuda_version VARCHAR(10) NULL',
                'SELECT 1');
            PREPARE stmt FROM @stmt;
            EXECUTE stmt;
            DEALLOCATE PREPARE stmt;
            """,
            reverse_sql="SELECT 1;"
        ),
        migrations.RunSQL(
            """
            SELECT COUNT(*) INTO @exist_cuda_available FROM information_schema.COLUMNS 
            WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'container_dockerimage' AND COLUMN_NAME = 'cuda_available';
            
            SET @stmt = IF(@exist_cuda_available = 0, 
                'ALTER TABLE container_dockerimage ADD COLUMN cuda_available BOOLEAN DEFAULT FALSE',
                'SELECT 1');
            PREPARE stmt FROM @stmt;
            EXECUTE stmt;
            DEALLOCATE PREPARE stmt;
            """,
            reverse_sql="SELECT 1;"
        ),
    ] 