# Generated by Django 4.2.18 on 2025-04-09 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('container', '0009_remove_dockerimage_cuda_version_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dockerimage',
            name='cuda_version',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='CUDA版本'),
        ),
        migrations.AddField(
            model_name='dockerimage',
            name='pytorch_version',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='PyTorch版本'),
        ),
    ]
